version: 2

updates:
  - package-ecosystem: pip
    directory: /cicd
    target-branch: dev
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /cicd
    target-branch: test
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    target-branch: test
    schedule:
      interval: weekly
